name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build
        run: npm install
      - name: Deploy to gh-pages
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name thegecko
          git config --global user.email github@thegecko.org
          git add .
          git add --force dist
          git stash save
          git checkout gh-pages
          git pull
          git merge main --no-commit -X theirs
          git checkout stash -- .
          git commit --allow-empty --message "Automatic Deployment"
          git push
